"use client";

import * as React from "react";
import { Loader2, HelpCircle, Activity, ChevronDown, BookOpen, MessageSquare, ShieldCheck, HelpCircle as HelpIcon } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "How does the PDF Processing pipeline work?",
    answer: "When you upload a PDF, the file is saved securely to Supabase Storage. This triggers a background event managed by Inngest. LangChain then extracts the text content, breaks it into semantic chunks, generates vector embeddings using Gemini, and indexes those embeddings in Qdrant. Finally, AI generates a structured summary and keywords, storing them back in PostgreSQL."
  },
  {
    question: "Why is my paper stuck in 'processing' status?",
    answer: "This usually occurs if the background worker orchestration is not running. In local development, make sure the Inngest local development server is running (`npm run inngest:dev` or `npx inngest-cli@latest dev`). In production, check the Inngest cloud dashboard to ensure webhooks are properly routed and signed."
  },
  {
    question: "What are the token limits for Literature Review or comparisons?",
    answer: "We currently use GPT-4o which supports a large context window. However, running a comparative synthesis on more than 50 large documents simultaneously might exceed rate limits. To keep responses fast and reliable, the AI Orchestrator retrieves the top relevant chunks across all papers dynamically using semantic search."
  },
  {
    question: "Can I parse scanned documents or image-only PDFs?",
    answer: "LitLens AI uses text-based parsing (`pdf-parse`) to extract content. Scanned documents or image-only PDFs without an OCR layer will return empty text. If this occurs, we recommend OCR-processing the document before upload."
  },
  {
    question: "How do I secure my Inngest webhooks in production?",
    answer: "Inngest webhooks are secured automatically using HMAC signature validation. Ensure that the `INNGEST_SIGNING_KEY` environment variable generated by the Inngest dashboard is correctly supplied to your production hosting provider (e.g. Vercel) to authorize incoming triggers."
  }
];

interface HealthPayload {
  status: string;
  environment?: string;
  timestamp?: string;
  services?: {
    database: string;
    ai_provider: string;
  };
}

export default function HelpPage() {
  const [expandedIndex, setExpandedIndex] = React.useState<number | null>(null);
  const [healthData, setHealthData] = React.useState<HealthPayload | null>(null);
  const [isCheckingHealth, setIsCheckingHealth] = React.useState(false);

  const fetchHealth = React.useCallback(async () => {
    setIsCheckingHealth(true);
    try {
      const res = await fetch("/api/health");
      const data = await res.json();
      setHealthData(data);
    } catch (err) {
      console.error("Health check fetch failed:", err);
      setHealthData({
        status: "down",
        services: { database: "down", ai_provider: "unconfigured" }
      });
    } finally {
      setIsCheckingHealth(false);
    }
  }, []);

  React.useEffect(() => {
    let active = true;
    const run = async () => {
      setIsCheckingHealth(true);
      try {
        const res = await fetch("/api/health");
        const data = await res.json();
        if (active) setHealthData(data);
      } catch (err) {
        console.error("Health check fetch failed:", err);
        if (active) {
          setHealthData({
            status: "down",
            services: { database: "down", ai_provider: "unconfigured" }
          });
        }
      } finally {
        if (active) setIsCheckingHealth(false);
      }
    };
    run();
    return () => { active = false; };
  }, []);

  const toggleExpand = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  return (
    <div className="flex-1 space-y-8 p-4 sm:p-8 pt-6 max-w-5xl mx-auto w-full">
      {/* Header */}
      <div className="mb-2">
        <h2 className="text-3xl font-bold tracking-tight">Help & Support</h2>
        <p className="text-muted-foreground mt-1 text-sm">
          Access literature search guides, check system configurations, or diagnose pipeline health.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* FAQ Accordion List (Left Column) */}
        <div className="md:col-span-2 space-y-4">
          <div className="flex items-center space-x-2 pb-2 border-b border-outline-variant">
            <HelpIcon className="h-5 w-5 text-primary" />
            <h3 className="font-semibold text-lg">Frequently Asked Questions</h3>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, index) => {
              const isExpanded = expandedIndex === index;
              return (
                <div 
                  key={index}
                  className="border border-outline-variant/60 rounded-xl bg-surface/20 overflow-hidden transition-all duration-300"
                >
                  <button
                    onClick={() => toggleExpand(index)}
                    className="w-full px-5 py-4 flex items-center justify-between text-left font-medium text-sm hover:bg-surface/50 transition-colors focus:outline-none cursor-pointer"
                  >
                    <span>{faq.question}</span>
                    <ChevronDown 
                      className={`h-4 w-4 text-muted-foreground transition-transform duration-300 ${isExpanded ? 'rotate-180 text-primary' : ''}`}
                    />
                  </button>
                  <div 
                    className={`transition-all duration-300 ease-in-out ${isExpanded ? 'max-h-60 border-t border-outline-variant/40' : 'max-h-0'}`}
                    style={{ overflow: 'hidden' }}
                  >
                    <div className="px-5 py-4 text-sm text-on-surface-variant leading-relaxed">
                      {faq.answer}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* System Diagnostics & Links (Right Column) */}
        <div className="space-y-6 md:col-span-1">
          {/* Diagnostics Panel */}
          <div className="bg-surface/30 border border-outline-variant/60 rounded-xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-outline-variant/40">
              <div className="flex items-center space-x-2">
                <Activity className="h-4.5 w-4.5 text-primary" />
                <h4 className="font-semibold text-sm">System Diagnostics</h4>
              </div>
              <button
                onClick={fetchHealth}
                disabled={isCheckingHealth}
                className="text-[11px] font-semibold text-primary hover:underline cursor-pointer disabled:opacity-50"
              >
                {isCheckingHealth ? "Checking..." : "Refresh"}
              </button>
            </div>

            <div className="space-y-4">
              {/* Overall status */}
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">Orchestrator Status</span>
                {isCheckingHealth ? (
                  <Loader2 className="h-4 w-4 animate-spin text-primary" />
                ) : (
                  <div className="flex items-center gap-1.5">
                    <div className={`h-2.5 w-2.5 rounded-full ${healthData?.status === "healthy" ? 'bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.5)]' : 'bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]'}`} />
                    <span className="text-xs font-semibold capitalize">{healthData?.status || "Unknown"}</span>
                  </div>
                )}
              </div>

              {/* Database status */}
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">Supabase Database</span>
                <span className={`text-xs font-semibold capitalize ${healthData?.services?.database === "up" ? 'text-green-500' : 'text-red-500'}`}>
                  {healthData?.services?.database === "up" ? "Connected" : "Disconnected"}
                </span>
              </div>

              {/* AI Key status */}
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">Gemini Key</span>
                <span className={`text-xs font-semibold capitalize ${healthData?.services?.ai_provider === "configured" ? 'text-green-500' : 'text-yellow-500'}`}>
                  {healthData?.services?.ai_provider === "configured" ? "Configured" : "Missing"}
                </span>
              </div>

              {/* Node environment */}
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">Environment</span>
                <span className="text-xs font-semibold font-mono capitalize">{healthData?.environment || "development"}</span>
              </div>
            </div>
          </div>

          {/* Quick Guides & Support */}
          <div className="bg-surface/30 border border-outline-variant/60 rounded-xl p-5 shadow-sm space-y-4">
            <h4 className="font-semibold text-sm pb-2 border-b border-outline-variant/40">Quick Support Resources</h4>
            <div className="space-y-3">
              <a 
                href="https://github.com/shreyas/litlens-ai" 
                target="_blank" 
                rel="noreferrer"
                className="flex items-center gap-3 p-2.5 rounded-lg border border-outline-variant/30 hover:bg-surface/50 transition-all text-xs font-medium cursor-pointer"
              >
                <BookOpen className="h-4 w-4 text-primary" />
                <span>Read Documentation</span>
              </a>
              <div className="flex items-center gap-3 p-2.5 rounded-lg border border-outline-variant/30 text-xs font-medium text-muted-foreground cursor-not-allowed">
                <MessageSquare className="h-4 w-4" />
                <span>Chat with Support (Soon)</span>
              </div>
              <div className="flex items-center gap-3 p-2.5 rounded-lg border border-outline-variant/30 text-xs font-medium text-muted-foreground cursor-not-allowed">
                <ShieldCheck className="h-4 w-4" />
                <span>Service Status SLA (Soon)</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
