import { Paper, Project } from "./types";

export const MOCK_PROJECTS: readonly Project[] = [
  {
    id: "proj_1",
    userId: "user_123",
    title: "Large Language Models in Healthcare",
    description: "Literature review on the applications and limitations of LLMs in clinical settings.",
    status: "active",
    createdAt: "2023-10-01T12:00:00Z",
    updatedAt: "2023-10-15T09:30:00Z",
  },
  {
    id: "proj_2",
    userId: "user_123",
    title: "Quantum Computing Advances",
    description: "Survey of recent breakthroughs in quantum error correction.",
    status: "active",
    createdAt: "2023-11-05T08:15:00Z",
    updatedAt: "2023-11-10T14:20:00Z",
  },
];

export const MOCK_PAPERS: readonly Paper[] = [
  {
    id: "paper_1",
    projectId: "proj_1",
    userId: "user_123",
    title: "Attention Is All You Need",
    authors: [
      { name: "Ashish Vaswani" },
      { name: "Noam Shazeer" },
      { name: "Niki Parmar" },
    ],
    abstract: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.",
    year: 2017,
    journal: "Advances in Neural Information Processing Systems",
    tags: ["Deep Learning", "NLP", "Transformers"],
    status: "completed",
    summary: {
      abstract: "Introduces the Transformer architecture relying solely on attention mechanisms.",
      methodology: "Replaces recurrent layers with multi-head self-attention.",
      datasets: ["WMT 2014 English-to-German", "WMT 2014 English-to-French"],
      keyFindings: ["Achieved state-of-the-art BLEU score", "Significantly less training time required"],
    },
    fileUrl: "https://example.com/paper1.pdf",
    fileName: "attention_is_all_you_need.pdf",
    fileSize: 1048576, // 1MB
    mimeType: "application/pdf",
    uploadedAt: "2023-10-02T10:00:00Z",
    embeddingCreated: true,
    createdAt: "2023-10-02T10:00:00Z",
    updatedAt: "2023-10-02T10:05:00Z",
  },
  {
    id: "paper_2",
    projectId: "proj_1",
    userId: "user_123",
    title: "Language Models are Few-Shot Learners",
    authors: [
      { name: "Tom B. Brown" },
      { name: "Benjamin Mann" },
      { name: "Nick Ryder" },
    ],
    abstract: "Recent work has demonstrated substantial gains on many NLP tasks and benchmarks by pre-training on a large corpus of text followed by fine-tuning on a specific task. While typically task-agnostic in architecture, this method still requires task-specific fine-tuning datasets of thousands or tens of thousands of examples. By contrast, humans can generally perform a new language task from only a few examples.",
    year: 2020,
    journal: "Advances in Neural Information Processing Systems",
    tags: ["LLM", "Few-Shot Learning", "GPT-3"],
    status: "completed",
    summary: {
      abstract: "Presents GPT-3, an autoregressive language model with 175 billion parameters.",
      methodology: "Scaling up language models to improve few-shot performance without gradient updates.",
      datasets: ["Common Crawl", "WebText2", "Books1", "Books2", "Wikipedia"],
      keyFindings: ["Strong performance on many NLP datasets", "Demonstrates capability in translation, Q&A, and reasoning"],
    },
    fileUrl: "https://example.com/paper2.pdf",
    fileName: "gpt3_few_shot.pdf",
    fileSize: 4194304, // 4MB
    mimeType: "application/pdf",
    uploadedAt: "2023-10-05T14:30:00Z",
    embeddingCreated: true,
    createdAt: "2023-10-05T14:30:00Z",
    updatedAt: "2023-10-05T14:45:00Z",
  },
  {
    id: "paper_3",
    projectId: "proj_2",
    userId: "user_123",
    title: "Surface codes: Towards practical large-scale quantum computation",
    authors: [
      { name: "Austin G. Fowler" },
      { name: "Matteo Mariantoni" },
      { name: "John M. Martinis" },
    ],
    abstract: "We review surface codes, the leading quantum error correction scheme. Surface codes have a high threshold error rate of approximately 1%, requiring only nearest-neighbor interactions on a 2D square lattice of qubits.",
    year: 2012,
    journal: "Physical Review A",
    tags: ["Quantum Computing", "Error Correction"],
    status: "completed",
    summary: {
      abstract: "A comprehensive review of surface codes for quantum error correction.",
      methodology: "Theoretical analysis of topological error correction on 2D lattices.",
      keyFindings: ["High error threshold (~1%)", "Feasible with current 2D superconducting architectures"],
    },
    fileUrl: "https://example.com/paper3.pdf",
    fileName: "surface_codes.pdf",
    fileSize: 2097152, // 2MB
    mimeType: "application/pdf",
    uploadedAt: "2023-11-06T09:15:00Z",
    embeddingCreated: true,
    createdAt: "2023-11-06T09:15:00Z",
    updatedAt: "2023-11-06T09:20:00Z",
  },
  {
    id: "paper_4",
    projectId: "proj_1",
    userId: "user_123",
    title: "Med-PaLM: Large Language Models Encode Clinical Knowledge",
    authors: [
      { name: "Karan Singhal" },
      { name: "Shekoofeh Azizi" },
      { name: "Tao Tu" },
    ],
    abstract: "Large language models (LLMs) have demonstrated impressive capabilities in natural language understanding and generation, but their ability to encode clinical knowledge and perform well on medical question answering tasks remains an active area of research.",
    year: 2022,
    journal: "Nature",
    tags: ["Healthcare", "LLM", "Medical AI"],
    status: "summarizing",
    fileUrl: "https://example.com/paper4.pdf",
    fileName: "med_palm_clinical.pdf",
    fileSize: 3145728, // 3MB
    mimeType: "application/pdf",
    uploadedAt: "2023-10-10T11:00:00Z",
    embeddingCreated: true,
    createdAt: "2023-10-10T11:00:00Z",
    updatedAt: "2023-10-10T11:05:00Z",
  },
  {
    id: "paper_5",
    projectId: "proj_2",
    userId: "user_123",
    title: "Quantum supremacy using a programmable superconducting processor",
    authors: [
      { name: "Frank Arute" },
      { name: "Kunal Arya" },
      { name: "Ryan Babbush" },
    ],
    abstract: "The promise of quantum computers is that certain computational tasks might be executed exponentially faster on a quantum processor than on a classical processor. A fundamental challenge is to build a high-fidelity processor capable of running quantum algorithms in an exponentially large computational space.",
    year: 2019,
    journal: "Nature",
    tags: ["Quantum Supremacy", "Superconducting Qubits"],
    status: "processing",
    fileUrl: "https://example.com/paper5.pdf",
    fileName: "quantum_supremacy.pdf",
    fileSize: 5242880, // 5MB
    mimeType: "application/pdf",
    uploadedAt: "2023-11-10T15:00:00Z",
    embeddingCreated: false,
    createdAt: "2023-11-10T15:00:00Z",
    updatedAt: "2023-11-10T15:00:00Z",
  },
];